name: Video Downloader & Cutter Max 1080p

on:
  workflow_dispatch:
    inputs:
      link_youtube:
        description: 'Link Video Sumber'
        required: true
      waktu_mulai:
        description: 'Waktu Mulai (Contoh: 00:00:00)'
        required: true
        default: '00:00:00'
      waktu_selesai:
        description: 'Waktu Selesai (Contoh: 00:00:30)'
        required: true
        default: '00:00:30'

jobs:
  download_cutter:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Install Tools
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg jq curl
          sudo curl -L https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          yt-dlp -U

      - name: 4. Download & Cut Video (Max 1080p, Cepat 5x, Pakai Cookies)
        env:
          YT_COOKIES: ${{ secrets.YT_COOKIES }}
        run: |
          set +e

          if [ -n "$YT_COOKIES" ] && [ "$YT_COOKIES" != "KOSONG" ]; then
            echo "$YT_COOKIES" > cookies.txt
            COOKIE_ARG="--cookies cookies.txt"
            echo "✅ Cookies berhasil dimuat untuk bypass bot."
          else
            COOKIE_ARG=""
            echo "⚠️ PERINGATAN: YT_COOKIES kosong!"
          fi

          FIXED_UA="Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36"

          echo "🚀 Memulai download bagian ${{ github.event.inputs.waktu_mulai }} s/d ${{ github.event.inputs.waktu_selesai }} (Maksimal Resolusi 1080p)..."

          yt-dlp \
            $COOKIE_ARG \
            --js-runtime node \
            --force-ipv4 \
            --no-cache-dir \
            --user-agent "$FIXED_UA" \
            --extractor-args "youtube:player-client=android,web" \
            -N 5 \
            --download-sections "*${{ github.event.inputs.waktu_mulai }}-${{ github.event.inputs.waktu_selesai }}" \
            -f "bestvideo[height<=1080]+bestaudio/best[height<=1080]" \
            --merge-output-format mp4 \
            -o "hasil_potongan.mp4" \
            "${{ github.event.inputs.link_youtube }}"

          EXIT_CODE=$?
          rm -f cookies.txt

          if [ $EXIT_CODE -ne 0 ]; then
            echo "❌ Download gagal!"
            exit $EXIT_CODE
          fi

          echo "✅ Selesai! File 'hasil_potongan.mp4' berhasil dibuat."
          ls -lh hasil_potongan.mp4

      - name: 5. Upload Hasil Video ke Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: video-hasil-potongan
          path: hasil_potongan.mp4
          retention-days: 1 # File otomatis terhapus setelah 1 hari agar tidak memenuhi storage
          
